# Generated by Django 3.0.5 on 2020-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bloghiglight',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogshortdes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagealt',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
