# Generated by Django 3.0.5 on 2021-01-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201215_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogshortdes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
